### ISSUE TITLE
Can't start game

### ISSUE THREAD

**Issue by littlepianist** [nanite/ItShallNotTick#1]
### Mod version

1.0.10-build.11

### Forge mod loader version

1.18.2-40.1.0

### Repeatable?

- [X] Yes

### Link to log files

[crash-2022-05-04_20.09.14-server.txt](https://github.com/nanite/ItShallNotTick/files/8620226/crash-2022-05-04_20.09.14-server.txt)

### Steps to reproduce the issue

1.use the mod
2.crash before finish loading

### Description of the issue you are having

crash

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
It should be noted that currently the mod required FTB chunks to run. This will be optional in the next few releases. The mods still very experimental

**Comment by littlepianist** [comment]
thanks for your quick response!
