### ISSUE TITLE
Detected that a single server tick took 60.00 seconds (should be max 0.05); ItemEntity and ISNT

### ISSUE THREAD

**Issue by VenomiXeD** [nanite/ItShallNotTick#10]
### Mod version

 ItShallNotTick-1.0.20-build.21.jar

### Forge mod loader version

forge-1.18.2-40.1.51-universal.jar

### Repeatable?

- [X] Yes

### Link to log files

[crash-2022-07-27_10.06.18-server.txt](https://github.com/nanite/ItShallNotTick/files/9197746/crash-2022-07-27_10.06.18-server.txt)

### Steps to reproduce the issue

1. Run server
2. Leave it running, have some kind of mob farmer and make sure it's loaded with automatic systems killing them, dropping items(?)
3. ...Let it run in the background
4. Crash

### Description of the issue you are having

Server is running 24/7. However it cannot do that anymore because of the reason that **ISNT** causes a crash related to items and collision. With the error **java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)**

Assuming that one of the operations took more than 60 seconds which causes it to terminate the server. That is at least what I digged out from the crash report. 

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
Not a fault with my mod, it only shows up due to the way the mod works, you can fix the crash though by setting the max-tick-time in server.properties to -1

**Comment by VenomiXeD** [comment]
Actually this remains as an issue and the server console spams "Running X ticks behind or Y ms behind". Logging in to the server clearly doesn't work since the server is frozen. I'd argue this is not intended behaviour.

**Comment by MichaelHillcox** [comment]
Regardless of this fact, this mod is very unlikely to be the cause as we only show in the stacktrace due to the way the mod works. 

Please feel free to make a spark report (spark mod on curseforge) and we can see if we're the cause or not.

**Comment by VenomiXeD** [comment]
Found the issue. The server had an unhealthy amount of items sitting on the ground (More than 11k item entities, more than 400 endermans, 80 silver fishes)

The issue was resolved by deleting the mod and using kill command on items. Since removing the mod stopped the server from crashing so I could go in and fix it.
