### ISSUE TITLE
1.19 - Client Crash when joining the server

### ISSUE THREAD

**Issue by Daltaxy** [nanite/ItShallNotTick#11]
### Mod version

ItShallNotTick-1.0.6-build.29.jar

### Forge mod loader version

41.1.0

### Repeatable?

- [ ] Yes

### Link to log files

[crash-2022-08-11_18.21.18-client.txt](https://github.com/nanite/ItShallNotTick/files/9310257/crash-2022-08-11_18.21.18-client.txt)

### Description of the issue you are having

I simply cannot log into my minecraft server. The server seems to have no issue, and doesn't crash. When I join, it simply says Connection lost to <player>.
Here is the Crashy link in case : https://crashy.net/qOw4BIkKpLJbMiHz3jR6
It is client-sided only, it appears. Right now I can't log in at all, but this isn't the first crash linked to ISNT. Any incompatibilities perhaps ? I use about 250 mods.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Not this mod. Please report to the author of ecologics

actual error: `java.lang.NullPointerException: Registry Object not present: ecologics:slippery`
