### ISSUE TITLE
[Issue] Server crash after updating ITSNT

### ISSUE THREAD

**Issue by Saereth** [nanite/ItShallNotTick#14]
### Mod version

1.18.2

### Forge mod loader version

40.1.73

### Repeatable?

- [X] Yes

### Link to log files

https://hastebin.com/yufugowite.rust

### Steps to reproduce the issue

We are getting some server crashes after updating ISNT, not sure if ITSNT is causing it or not but its the only non vanilla thing I'm seeing in the stack trace, lemme know what you think

People said this is happening when they go into dungeons 

### Description of the issue you are having

Random server crash possibly related to ISNT

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
No an issue caused by my mod, I dont touch entity ai so its likely another mod that does something with entity ai
