### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by Atlantispy** [nanite/ItShallNotTick#2]
While the FTB integration is nice, it would be more ideal if it was an optional dependency?

Is that possible?

**Comment by Gaz492** [comment]
Hopefully, in the next update or two it will be an optional dependency :)

**Comment by Atlantispy** [comment]
Great, thanks, and thanks for the quick response.

**Comment by Gaz492** [comment]
Once version 1.0.13 is on Curseforge in a few minutes it no longer hard depends on chunks :D
