### ISSUE TITLE
[Issue] [Log] Mixin config itshallnottick.mixins.json does not specify "minVersion" property

### ISSUE THREAD

**Issue by Lucky-56** [nanite/ItShallNotTick#20]
### Mod version

1.0.11-build.35

### Forge mod loader version

43.1.47

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/nanite/ItShallNotTick/files/9928097/latest.log)

### Steps to reproduce the issue

1. Enable the log in the launcher
2. Start game
3. Look at the log

### Description of the issue you are having

`Mixin config itshallnottick.mixins.json does not specify "minVersion" property` in log

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Not an issue, just a warning

**Comment by Lucky-56** [comment]
still something that could be fixed, is it not?
