### ISSUE TITLE
client mod required 

### ISSUE THREAD

**Issue by Bucky420** [nanite/ItShallNotTick#21]
### Mod version

1.18.2

### Forge mod loader version

latest

### Repeatable?

- [X] Yes

### Link to log files

N/A

### Steps to reproduce the issue

install this mod 

### Description of the issue you are having

the client need the mod making this hole project pointless 

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
It's required as a client mod as I don't render the mobs that are not ticking. Otherwise, you would just have a bunch of mobs standing still looking like they are broken which would lead to more bug reports

**Comment by Bucky420** [comment]
> It's required as a client mod as I don't render the mobs that are not ticking. Otherwise, you would just have a bunch of mobs standing still looking like they are broken which would lead to more bug reports

so this does nothing with TE? not to worryed about mobs on a island server
