### ISSUE TITLE
[Issue] Item entities desync

### ISSUE THREAD

**Issue by jamesjimmy88** [nanite/ItShallNotTick#3]
### Mod version

1.0.14 build 17

### Forge mod loader version

40.1.19

### Repeatable?

- [X] Yes

### Link to log files

Nothing relevant in the log

### Steps to reproduce the issue

Just look at dropped items before they stop falling - be it from being tossed by a player, dropped by a monster, dispensed, etc.

### Description of the issue you are having

There appears to be some sort of server-client desync that makes item go constantly in and out of sync.
Here's a video of the issue: https://streamable.com/17crgr
The game is running at 20 tps and there doesn't appear to be any issue with non-item entities.
Tested on a new instance with default settings and no other mod.
[EDIT] I Just to confirm it, I tried adding "minecraft:item" to the entityIgnoreList entry in the mod's config and the issue disappears.

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
This is technically not an issue, as I cache the item collision for a second, as the calls to check item collisions are done every tick and is rather taxing on a server.
It may be possible for me to check if it's on the ground first before caching the collisions, but It's something I would need to look at.
