### ISSUE TITLE
[Quick Question]

### ISSUE THREAD

**Issue by X-Niter** [nanite/ItShallNotTick#4]
### Mod version

1.0.20-build.21

### Forge mod loader version

1.18.2-40.1.19

### Repeatable?

- [X] Yes

### Link to log files

Not Applicable 

### Steps to reproduce the issue

Not Applicable 

### Description of the issue you are having

Hey there I just had a quick question, 

Your mod description only mentioned 'This improves the server performance'.

I just wanted to clarify on if this is server side or client side, or both. 

Sorry for the small question.

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
It's both, the mod stops entities from ticking if they are too far from the player and if the entity is not ticking, it will stop it from rendering.

**Comment by X-Niter** [comment]
Understood thank you very much
