### ISSUE TITLE
[Feature Request] Specific Mod Ignore

### ISSUE THREAD

**Issue by NBZion** [nanite/ItShallNotTick#8]
### Feature Description

Add in the config for specific modids to be ignored e.g. create(uses entities i think) and etc.

**Comment by Gaz492** [comment]
> ### Feature Description
> 
> Add in the config for specific modids to be ignored e.g. create(uses entities i think) and etc.

This can already be done by adding `modid:*` to the `entityIgnoreList` setting in the config.
There should be an example for this there as well that includes create and other mods
